# Generated by Django 5.1.3 on 2024-11-10 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_delete_vote'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoterCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_codes', to='poll.poll')),
            ],
        ),
    ]
