# Generated by Django 5.1.3 on 2025-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
    ]
