# Generated by Django 5.1.3 on 2024-11-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_votercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='VoterCode',
        ),
    ]
