# Generated by Django 5.1.3 on 2025-05-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_vote_options_vote_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='payment_verified',
        ),
    ]
