# Generated by Django 5.1.7 on 2025-06-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_available_balance_user_total_collected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_collected',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_withdrawn',
        ),
    ]
