# Generated by Django 5.1.3 on 2025-05-30 16:38

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('poll_type', models.CharField(choices=[('creator-pay', 'Creator-Pay'), ('voters-pay', 'Voters-Pay')], max_length=20)),
                ('expected_voters', models.PositiveIntegerField(blank=True, null=True)),
                ('voting_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('setup_fee', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('active', models.BooleanField(default=False)),
                ('poll_image', cloudinary.models.CloudinaryField(help_text='Poll image', max_length=255, verbose_name='image')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('nominee_code', models.CharField(max_length=15, unique=True)),
                ('contestant_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contestants', to='poll.poll')),
            ],
        ),
    ]
