# Generated by Django 5.1.3 on 2024-11-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='poll_images/'),
        ),
    ]
