# Generated by Django 5.1.3 on 2024-11-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_poll_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='image',
            new_name='poll_image',
        ),
    ]
