# Generated by Django 5.1.3 on 2024-11-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='setup_fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
