# Generated by Django 5.1.3 on 2024-11-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_poll_setup_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='contestant_images/'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='voting_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
