# Generated by Django 5.1.3 on 2024-12-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_rename_image_poll_poll_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='award',
        ),
    ]
