# Generated by Django 5.1.3 on 2024-11-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_contestant_image_alter_poll_voting_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='nominee_code',
        ),
    ]
