# Generated by Django 5.1.3 on 2025-03-09 20:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_remove_contestant_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
