# Generated by Django 5.1.3 on 2025-05-29 14:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_alter_contestant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='poll',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
