# Generated by Django 5.1.3 on 2024-11-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_remove_contestant_nominee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='nominee_code',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
