# Generated by Django 5.1.3 on 2025-05-29 15:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_poll_image_poll_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='image',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='image',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='website',
        ),
        migrations.AddField(
            model_name='contestant',
            name='contestant_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
