# Generated by Django 5.1.3 on 2024-11-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_contestant_nominee_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
